# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       doxygen
Summary:    Automated C, C++, and Java Documentation Generator
Version:    1.7.6.1
Release:    1
Group:      Development/Tools
License:    GPLv2+
URL:        http://www.stack.nl/~dimitri/doxygen/
Source0:    http://ftp.stack.nl/pub/users/dimitri/doxygen-%{version}.src.tar.gz
Source100:  doxygen.yaml
Patch0:     doxygen-1.7.1-config.patch
Patch1:     doxygen-1.7.0-modify_footer.patch
BuildRequires:  gettext
BuildRequires:  flex
BuildRequires:  bison


%description
Doxygen is a documentation system for C, C++, Java, and IDL. It can
generate an online class browser (in HTML) and an offline reference
manual (in LaTeX) from a set of documented source files. The
documentation is extracted directly from the sources. Doxygen is
developed on a Linux platform, but it runs on most other UNIX flavors
as well. An executable for Windows 95/NT is also available.




%prep
%setup -q -n %{name}-%{version}

# doxygen-1.7.1-config.patch
%patch0 -p1
# doxygen-1.7.0-modify_footer.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
unset QTDIR
./configure --prefix %{_prefix} --shared --release
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%attr(444,root,root) %doc %{_mandir}/man1/doxygen.1.*
%attr(444,root,root) %doc %{_mandir}/man1/doxytag.1.*
%attr(755,root,root) /usr/bin/*
# << files


